### PR TITLE
Finished draft sdk documentation! update README

### PR DESCRIPTION
**Pull request by Renewwen**
Finished draft js-sdk documentation!
put `Document document creation process` to the README.

### CODE REVIEW

**Comment by Renewwen** [comment]
fixed some description issues...

**Comment by Renewwen** [comment]
**three things:**
1. beautify index page 
2. simplify the navigation bar
3. Add @annotation to each page, prepare for next step work

**Comment by Renewwen** [comment]
Start to revamp and create examples for our js-SDK.
- Test the APIs one by one to understand how each one work,
- Identify/list the missing feature.  

Specifically, I am starting from the Blockchain class in the harmony-core package.
image

**Comment by Renewwen** [comment]
### Position: 
`harmony-core/Blockchain`

### New Issues:
[The param "returnObject" is not work in functions: getBlockbyHash and getBlockbyNumber](https://github.com/harmony-one/sdk/issues/18#issue-561321391)

### Has revamped:
```javascript
hmy.blockchain.getBalance()
hmy.blockchain.getBlockNumber()
hmy.blockchain.getBlockByHash()
hmy.blockchain.getBlockByNumber()
hmy.blockchain.getBlockTransactionCountByHash()
hmy.blockchain.getBlockTransactionCountByNumber()
hmy.blockchain.getTransactionByBlockHashAndIndex()
hmy.blockchain.getTransactionByBlockNumberAndIndex()
hmy.blockchain.getTransactionByHash()
hmy.blockchain.getTransactionReceipt()
hmy.blockchain.getCxReceiptByHash()
hmy.blockchain.getCode()
hmy.blockchain.net_peerCount()
hmy.blockchain.net_version()
hmy.blockchain.getProtocolVersion()
```

### Has hidden:
```javascript
hmy.blockchain.constructor()
hmy.blockchain.setMessage()
hmy.blockchain.getRpcResult()
```

**Comment by Renewwen** [comment]
**=== 2/7 ===**
### 1. Index pages and hierarchy rebuild
image
### 2. APIs revamped
image

**Comment by LeoHChen** [comment]
Resolved the merge conflict in another PR. https://github.com/harmony-one/sdk/pull/20

**Pull request closed without merging**
